### ISSUE TITLE
New input file for GB with 4 species

### ISSUE THREAD

**Issue by MaC-Perez** [MaC-Perez/Hydra-self-testing#1]
Hi @sgaichas!

We talk about Hydra selftesting in our meeting today, and for that I need a new input files for Georges bank including only 4 species (mackerel, herring, spiny dogfish and cod). Could you please create that file for me?. 

Thank you so much!

**Comment by sgaichas** [comment]
Yes I can do that. Do you want 5 length bins in the dataset? And I will leave all the other settings as is (fleets, etc)?

**Comment by MaC-Perez** [comment]
@sgaichas  Yes, 5 bins should be ok and all other settings the same... thanks!

**Comment by sgaichas** [comment]
ok, that should be all in the inputs folder here, please let me know if anything looks broken
853c8a82f914ddb0611aaf97b6ab39b9573f4894

**Comment by MaC-Perez** [comment]
thanks @sgaichas !
